### ISSUE TITLE
usdKatana headers are not installed

### ISSUE THREAD

**Issue by sopvop** [TheFoundryVisionmongers/KatanaUsdPlugins#1]
usdKatana headers are not installed, and you can't compile plugins to usdKatana without it.

Build system in pxr repo installs headers for PUBLIC_CLASSES.

**Comment by JamesPedFoundry** [comment]
Hi sopvop,

Thanks for raising this issue, I have raised an internal bug for this with the ID #420783 for us to track and fix this issue.

Cheers,
James

**Comment by JamesPedFoundry** [comment]
Hi sopvop,

We have patched this bug in the latest update to v19.11_fn2, all headers under the "PUBLIC_HEADERS" section will now be installed as expected.  Closing the issue.

Cheers,
James
