### ISSUE TITLE
Build system requires cmake config modules for TBB and Python, without fallback to FindX modules

### ISSUE THREAD

**Issue by sopvop** [TheFoundryVisionmongers/KatanaUsdPlugins#2]
Build system requires cmake config modules for TBB and Python, without fallback to FindX modules.
Which is surprising and is not documented in BUILDING.md.
Also katana distribution doesn't seem to provide these modules for bundled python and tbb.

**Comment by JamesPedFoundry** [comment]
Hi sopvop,

Thanks for raising this issue, we have raised an internal ticket to support FindX modules as well as using CMake configs.

The internal ticket number is: #420782

Cheers,
James

**Comment by JamesPedFoundry** [comment]
Hi sopvop, 
We have updated our BUILDING.md file, and our CMakefiles to allow for better support of non cmake .config file setups.  Let us know if the latest changes help!
A short description of the updates can be found in the CHANGELOG.md under the new release v19.11_fn2.

Closing the issue
