### ISSUE TITLE
Install headers for public classes

### ISSUE THREAD

**Issue by sirpalee** [TheFoundryVisionmongers/KatanaUsdPlugins#9]
At the moment running install on the project does not install the headers correctly. There will be a single `api.h` placed in `third_party\katana\lib\usd\include`. This makes difficult to compile plugins for usdKatana (scenegraph location decorators).

The preferred outcome is to install headers in `include\usdKatana` and `include\vtKatana`, this was supported in the old Pixar repository, but this is not added to `Support.cmake`.

**Comment by JamesPedFoundry** [comment]
Closing the issue, now fixed in v19.11_fn7 release under ID 440218
